version: '2'
services:
    db:
        image: mysql:5.7.40
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: tutorial-authentication
        volumes:
            - mysql:/var/lib/mysql
volumes:
    mysql:
